"""Sampling functions for port_typhoon_simulator DES.

All functions accept a numpy.random.Generator (from CRN stream separation in replication.py).
Never call np.random directly — always pass rng explicitly (CRN rule).

Parameters are loaded at import time from:
    data/models/input_dist_record.csv   (generated by scripts/fit_input_distributions.py)

All variables are fitted from data/raw/raw_data.xlsx (synthetic demo vessel-call
log -- see scripts/generate_synthetic_demo_data.py). No paper-only constants remain.

Time unit throughout: HOURS.
"""

from __future__ import annotations

import json
from pathlib import Path

import numpy as np
import pandas as pd

# ---------------------------------------------------------------------------
# Load fitted parameters from record
# ---------------------------------------------------------------------------

_RECORD_PATH = Path(__file__).parents[3] / "data" / "models" / "input_dist_record.csv"


def _load_fitted_params() -> dict:
    if not _RECORD_PATH.exists():
        raise FileNotFoundError(
            f"input_dist_record.csv not found at {_RECORD_PATH}.\n"
            "Run:  conda run -n somr python scripts/fit_input_distributions.py"
        )

    rec = pd.read_csv(_RECORD_PATH)

    # --- IAT ---
    iat_row   = rec[rec["variable"] == "inter_arrival_hrs"].iloc[0]
    iat_scale = float(json.loads(iat_row["params"])["scale"])

    # --- LPC groups ---
    lpc_rows = rec[rec["variable"] == "lpc"].sort_values("group")
    group_beta:   list[tuple[float, float]] = []
    group_ranges: list[tuple[int, int]]     = []
    group_n:      list[int]                 = []

    for _, row in lpc_rows.iterrows():
        p = json.loads(row["params"])
        group_beta.append((float(p["a"]), float(p["b"])))
        group_ranges.append((int(p["lo"]), int(p["hi"])))
        group_n.append(int(row["n"]))

    n_arr       = np.array(group_n, dtype=float)
    group_probs = n_arr / n_arr.sum()

    # --- Cranes per group ---
    qc_rows = rec[rec["variable"] == "qc_count"].sort_values("group")
    cranes_by_group: list[int] = [
        int(json.loads(row["params"])["value"]) for _, row in qc_rows.iterrows()
    ]

    # --- Idle before / after ---
    ib_row = rec[rec["variable"] == "idle_time_before_hrs"].iloc[0]
    ia_row = rec[rec["variable"] == "idle_time_after_hrs"].iloc[0]

    # --- Crane efficiency (per-crane, moves/hr) ---
    ce_row = rec[rec["variable"] == "crane_eff_moves_per_hr"].iloc[0]

    return {
        "iat_scale":        iat_scale,
        "group_probs":      group_probs,
        "group_ranges":     group_ranges,
        "group_beta":       group_beta,
        "cranes_by_group":  cranes_by_group,
        "idle_before_dist": ib_row["dist_name"],
        "idle_before_params": json.loads(ib_row["params"]),
        "idle_after_dist":  ia_row["dist_name"],
        "idle_after_params": json.loads(ia_row["params"]),
        "crane_eff_dist":   ce_row["dist_name"],
        "crane_eff_params": json.loads(ce_row["params"]),
    }


_FITTED = _load_fitted_params()

# ---------------------------------------------------------------------------
# Data-derived module-level constants
# ---------------------------------------------------------------------------

_IAT_SCALE: float = _FITTED["iat_scale"]

_GROUP_PROBS: np.ndarray = _FITTED["group_probs"]

_GROUP_RANGES: list[tuple[int, int]] = _FITTED["group_ranges"]

_GROUP_BETA: list[tuple[float, float]] = _FITTED["group_beta"]

_CRANES_BY_GROUP: list[int] = _FITTED["cranes_by_group"]

# TEU conversion factor (RESS 2018 validation: 2246.6 TEU/ship ÷ 1284.2 LPC/ship)
TEU_FACTOR: float = 1.75

# Distribution metadata for idle times and crane efficiency (used by tests)
_IDLE_BEFORE_DIST:   str  = _FITTED["idle_before_dist"]
_IDLE_BEFORE_PARAMS: dict = _FITTED["idle_before_params"]

_IDLE_AFTER_DIST:    str  = _FITTED["idle_after_dist"]
_IDLE_AFTER_PARAMS:  dict = _FITTED["idle_after_params"]

_CRANE_EFF_DIST:     str  = _FITTED["crane_eff_dist"]
_CRANE_EFF_PARAMS:   dict = _FITTED["crane_eff_params"]


# ---------------------------------------------------------------------------
# Generic distribution sampler
# ---------------------------------------------------------------------------

def _sample_dist(rng: np.random.Generator, dist_name: str, params: dict) -> float:
    """Sample one value from a named continuous distribution."""
    loc   = float(params.get("loc", 0.0))
    scale = float(params["scale"])

    if dist_name == "lognorm":
        return float(rng.lognormal(mean=np.log(scale), sigma=float(params["s"])) + loc)
    if dist_name == "norm":
        return float(rng.normal(loc=loc, scale=scale))
    if dist_name == "expon":
        return float(rng.exponential(scale=scale) + loc)
    if dist_name == "gamma":
        return float(rng.gamma(shape=float(params["a"]), scale=scale) + loc)
    raise ValueError(f"Unsupported dist_name in record: {dist_name!r}")


# ---------------------------------------------------------------------------
# Public sampling functions
# ---------------------------------------------------------------------------

def sample_inter_arrival(rng: np.random.Generator) -> float:
    """Inter-arrival time in hours. Exponential fitted from the demo vessel-call log."""
    return float(rng.exponential(scale=_IAT_SCALE))


def sample_lpc_group(rng: np.random.Generator) -> int:
    """LPC group index 0–6, sampled from data-derived group probabilities."""
    return int(rng.choice(len(_GROUP_PROBS), p=_GROUP_PROBS))


def sample_lpc(rng: np.random.Generator, group: int) -> int:
    """LPC (crane moves per vessel call) for the given group index (0–6).

    Uses Beta distribution within [lo, hi] range fitted from the demo vessel-call log.
    Groups 5–6 use Beta(1,1) = Uniform — small-sample fallback (n < 30).
    Returns integer (LPC is a count).
    """
    lo, hi       = _GROUP_RANGES[group]
    alpha, beta_ = _GROUP_BETA[group]
    value        = lo + (hi - lo) * rng.beta(alpha, beta_)
    return int(round(value))


def cranes_for_group(group: int) -> int:
    """Crane count allocated to a vessel call based on its LPC group.

    Deterministic — rounded mean QC from the demo vessel-call log.
    """
    return _CRANES_BY_GROUP[group]


def sample_crane_efficiency_lifts_per_hr(rng: np.random.Generator) -> float:
    """Per-crane efficiency in moves per hour.

    Fitted as Normal from raw_data.xlsx: crane_eff = LPC / (ops_time_hrs × qc_count).
    Mean ≈ 20.2 moves/hr/crane.  Clipped at 0.1 to prevent non-positive values.
    """
    val = _sample_dist(rng, _CRANE_EFF_DIST, _CRANE_EFF_PARAMS)
    return max(val, 0.1)


def sample_idle_before(rng: np.random.Generator) -> float:
    """Idle time before service starts, in hours.

    Lognormal fitted from raw_data.xlsx: idle_before = Commence − ATB.
    Mean ≈ 0.54 hrs (32 min).
    """
    return max(_sample_dist(rng, _IDLE_BEFORE_DIST, _IDLE_BEFORE_PARAMS), 0.0)


def sample_idle_after(rng: np.random.Generator) -> float:
    """Idle time after service ends, in hours.

    Lognormal fitted from raw_data.xlsx: idle_after = ATD − Complete.
    Mean ≈ 0.97 hrs (58 min).
    """
    return max(_sample_dist(rng, _IDLE_AFTER_DIST, _IDLE_AFTER_PARAMS), 0.0)


def sample_disruption_hrs(
    rng: np.random.Generator,
    disruption_days_min: int,
    disruption_days_max: int,
) -> float:
    """Disruption duration in hours. Uniform(min_days, max_days) × 24.

    If min == max == 0, returns 0.0 (no disruption scenario).
    """
    if disruption_days_min == disruption_days_max:
        return float(disruption_days_min * 24)
    days = rng.uniform(disruption_days_min, disruption_days_max)
    return days * 24.0
